# Generated by Django 6.0.7 on 2026-07-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de pedidos por día. 0 = sin límite.'),
        ),
    ]
