# Generated by Django 6.0.7 on 2026-07-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_max_orders_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_products', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('max_orders_per_day', models.PositiveIntegerField(default=0)),
                ('has_mp_integration', models.BooleanField(default=True)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.plan'),
        ),
    ]
