# Generated by Django 6.0.7 on 2026-07-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='accent_color',
            field=models.CharField(default='#E8889A', max_length=7),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bg_color',
            field=models.CharField(default='#FDF6EC', max_length=7),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='primary_color',
            field=models.CharField(default='#3D1A0E', max_length=7),
        ),
    ]
